name: Fitness Tracker CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Root Dependencies
        run: npm install

      - name: Install Server Dependencies
        run: |
          cd server
          npm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=fitness-tracker
            -Dsonar.projectName=Fitness_Tracker
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**

      - name: Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
